# action 名称
name: Publish and Release

# 当代码合并到master分支时执行以下脚本
on:
  push:
    branches: [master]


# 任务
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 关键权限
    steps: 
      - name: 检查master分支
        uses: actions/checkout@master

      - name: 设置Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org

      - name: 安装依赖
        run: npm install

      - name: 构建packages
        run: npm run lib

      - name: 发布NPM包
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish

      - name: publish 成功通知
        run: echo npm 推送成功

      - name: 读取当前版本号
        id: version
        uses: ashley-taylor/read-json-property-action@v1.2
        with:
          path: ./package.json
          property: version

      - name: 创建GitHub Release
        id: create_release
        # uses: actions/create-release@latest
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.value }}
          name: v${{ steps.version.outputs.value }}
          # release_name: v${{ steps.version.outputs.value }}
          draft: false
          prerelease: false

